### ISSUE TITLE
Consider providing a cli for local generation

### ISSUE THREAD

**Issue by bebraw** [thien-do/typed.tw#15]
I set up a quick script to avoid using the web service:

```js
#!/usr/bin/env node
const { getSource } = require("typed-tailwind-convert");

const stdin = process.openStdin();

function convert() {
  stdin.setEncoding("utf8");
  stdin.on("data", data => {
    getSource(data)
      .then(console.log)
      .catch(console.error);
  });
}

convert();
```

**Usage:**

```bash
./convert < tailwind.config.js > src/tw.ts
```

Maybe it would be handy to include something like this to `typed-tailwind-convert`?

**Comment by dvkndn** [comment]
yub thank you. Let me add it to the repo 👍

**Comment by fvanwijk** [comment]
Isn't it possible to generate this as part of the build system (loader?)? I don't want to generate a new file every time I change something in my Tailwind config file.

**Comment by dvkndn** [comment]
@fvanwijk it's possible, even now. I've just don't have the time to make it yet recently :(

The reason I went with the current approach is because I used CRA and Nextjs and I prefer to not intercept with their setup (so typed.tw is like a standalone app).

Actually the [current webpack-loader](https://github.com/dvkndn/typed.tw/tree/master/webpack-loader) could already do the second half (inlining the values). I need to find some time to add the first half (generate Tw.ts from the config)

**Comment by fvanwijk** [comment]
Did you know CRA includes `babel-macro-plugin` so you could add transforms without having to adjust the config (which isn't possible with CRA).
So it might be good to look into that.

`tw.macro` which I'm using is also making use of this. Since 1.0.0 release it is possible to do simple template string interpolation, so it is finally possible to do:
```
<div tw={Tw().textGray().bgRedDark()}>Content</div>
```

Keep up the good work.

**Comment by dvkndn** [comment]
wow thanks @fvanwijk I didn't know that! Wow this should be a game changer for me! The big goal from beginning is to use this with CRA
